In [2]:
import pandas as pd

In [40]:
df = pd.read_csv("datasets/dataset_mood_smartphone.csv", sep=",", encoding="utf-8")

# only take columns: id, time, variable, value
df = df[['id', 'time', 'variable', 'value']]

In [43]:
df['aux_index'] = df.groupby(['id', 'time', 'variable']).cumcount()
df

             id                     time        variable   value  aux_index
0       AS14.01  2014-02-26 13:00:00.000            mood   6.000          0
1       AS14.01  2014-02-26 15:00:00.000            mood   6.000          0
2       AS14.01  2014-02-26 18:00:00.000            mood   6.000          0
3       AS14.01  2014-02-26 21:00:00.000            mood   7.000          0
4       AS14.01  2014-02-27 09:00:00.000            mood   6.000          0
...         ...                      ...             ...     ...        ...
376907  AS14.30  2014-04-11 07:51:16.948  appCat.weather   8.032          0
376908  AS14.30  2014-04-19 11:00:32.747  appCat.weather   3.008          0
376909  AS14.30  2014-04-26 10:19:07.434  appCat.weather   7.026          0
376910  AS14.30  2014-04-27 00:44:48.450  appCat.weather  23.033          0
376911  AS14.32  2014-04-07 18:25:14.036  appCat.weather  22.431          0

[376912 rows x 5 columns]

In [44]:
df[(df['id'] == 'AS14.01') & (df['time'] == '2014-04-17 11:00:00.000')]

,id,time,variable,value,aux_index
135,AS14.01,2014-04-17 11:00:00.000,mood,7.00000,0
136,AS14.01,2014-04-17 11:00:00.000,mood,6.00000,1
5776,AS14.01,2014-04-17 11:00:00.000,circumplex.arousal,-1.00000,0
5777,AS14.01,2014-04-17 11:00:00.000,circumplex.arousal,-2.00000,1
11419,AS14.01,2014-04-17 11:00:00.000,circumplex.valence,1.00000,0
11420,AS14.01,2014-04-17 11:00:00.000,circumplex.valence,0.00000,1
17558,AS14.01,2014-04-17 11:00:00.000,activity,0.05042,0

In [58]:
# Now pivot using the new auxiliary column as part of the index to ensure uniqueness
pivot_df = df.pivot(index=['id', 'time', 'aux_index'], columns='variable', values='value')

pivot_df

variable                                   activity  appCat.builtin  \
id      time                    aux_index
AS14.01 2014-02-17 12:04:42.394 0               NaN             NaN
        2014-02-17 18:28:25.520 0               NaN             NaN
        2014-02-18 09:29:51.257 0               NaN             NaN
        2014-02-19 14:43:30.575 0               NaN             NaN
        2014-02-19 17:29:10.378 0               NaN             NaN
...                                             ...             ...
AS14.33 2014-05-30 22:32:05.016 0               NaN             NaN
        2014-05-30 22:32:11.049 0               NaN           3.122
        2014-05-30 22:32:14.240 0               NaN           1.003
        2014-05-30 22:32:15.246 0               NaN           4.134
        2014-05-31 12:00:00.000 0               NaN             NaN

variable                                   appCat.communication  \
id      time                    aux_index
AS14.01 2014-02-17 12:04:42.394 0                           NaN
        2014-02-17 18:28:25.520 0                           NaN
        2014-02-18 09:29:51.257 0                           NaN
        2014-02-19 14:43:30.575 0                           NaN
        2014-02-19 17:29:10.378 0                           NaN
...                                                         ...
AS14.33 2014-05-30 22:32:05.016 0                           NaN
        2014-05-30 22:32:11.049 0                           NaN
        2014-05-30 22:32:14.240 0                           NaN
        2014-05-30 22:32:15.246 0                           NaN
        2014-05-31 12:00:00.000 0                           NaN

variable                                   appCat.entertainment  \
id      time                    aux_index
AS14.01 2014-02-17 12:04:42.394 0                           NaN
        2014-02-17 18:28:25.520 0                           NaN
        2014-02-18 09:29:51.257 0                           NaN
        2014-02-19 14:43:30.575 0                           NaN
        2014-02-19 17:29:10.378 0                           NaN
...                                                         ...
AS14.33 2014-05-30 22:32:05.016 0                           NaN
        2014-05-30 22:32:11.049 0                           NaN
        2014-05-30 22:32:14.240 0                           NaN
        2014-05-30 22:32:15.246 0                           NaN
        2014-05-31 12:00:00.000 0                           NaN

variable                                   appCat.finance  appCat.game  \
id      time                    aux_index
AS14.01 2014-02-17 12:04:42.394 0                     NaN          NaN
        2014-02-17 18:28:25.520 0                     NaN          NaN
        2014-02-18 09:29:51.257 0                     NaN          NaN
        2014-02-19 14:43:30.575 0                     NaN          NaN
        2014-02-19 17:29:10.378 0                     NaN          NaN
...                                                   ...          ...
AS14.33 2014-05-30 22:32:05.016 0                     NaN          NaN
        2014-05-30 22:32:11.049 0                     NaN          NaN
        2014-05-30 22:32:14.240 0                     NaN          NaN
        2014-05-30 22:32:15.246 0                     NaN          NaN
        2014-05-31 12:00:00.000 0                     NaN          NaN

variable                                   appCat.office  appCat.other  \
id      time                    aux_index
AS14.01 2014-02-17 12:04:42.394 0                    NaN           NaN
        2014-02-17 18:28:25.520 0                    NaN           NaN
        2014-02-18 09:29:51.257 0                    NaN           NaN
        2014-02-19 14:43:30.575 0                    NaN           NaN
        2014-02-19 17:29:10.378 0                    NaN           NaN
...                                                  ...           ...
AS14.33 2014-05-30 22:32:05.016 0                    NaN           NaN
        2014-05-30 22:32:11.049 0                    NaN           NaN
        2014-05-30 22:32:14.240 0                    NaN           NaN
        2014-05-30 22:32:15.246 0                    NaN           NaN
        2014-05-31 12:00:00.000 0                    NaN           NaN

variable                                   appCat.social  appCat.travel  \
id      time                    aux_index
AS14.01 2014-02-17 12:04:42.394 0                    NaN            NaN
        2014-02-17 18:28:25.520 0                    NaN            NaN
        2014-02-18 09:29:51.257 0                    NaN            NaN
        2014-02-19 14:43:30.575 0                    NaN            NaN
        2014-02-19 17:29:10.378 0                    NaN            NaN
...                                                  ...            ...
AS14.33 2014-05-30 22:32:05.016 0                    NaN            NaN
        2014-05-30 22:32:11.049 0                    NaN            NaN
        2014-05-30 22:32:14.240 0                    NaN            NaN
        2014-05-30 22:32:15.246 0                    NaN            NaN
        2014-05-31 12:00:00.000 0                    NaN            NaN

variable                                   appCat.unknown  appCat.utilities  \
id      time                    aux_index
AS14.01 2014-02-17 12:04:42.394 0                     NaN               NaN
        2014-02-17 18:28:25.520 0                     NaN               NaN
        2014-02-18 09:29:51.257 0                     NaN               NaN
        2014-02-19 14:43:30.575 0                     NaN               NaN
        2014-02-19 17:29:10.378 0                     NaN               NaN
...                                                   ...               ...
AS14.33 2014-05-30 22:32:05.016 0                     NaN             6.019
        2014-05-30 22:32:11.049 0                     NaN               NaN
        2014-05-30 22:32:14.240 0                     NaN               NaN
        2014-05-30 22:32:15.246 0                     NaN               NaN
        2014-05-31 12:00:00.000 0                     NaN               NaN

variable                                   appCat.weather  call  \
id      time                    aux_index
AS14.01 2014-02-17 12:04:42.394 0                     NaN   1.0
        2014-02-17 18:28:25.520 0                     NaN   1.0
        2014-02-18 09:29:51.257 0                     NaN   1.0
        2014-02-19 14:43:30.575 0                     NaN   1.0
        2014-02-19 17:29:10.378 0                     NaN   1.0
...                                                   ...   ...
AS14.33 2014-05-30 22:32:05.016 0                     NaN   NaN
        2014-05-30 22:32:11.049 0                     NaN   NaN
        2014-05-30 22:32:14.240 0                     NaN   NaN
        2014-05-30 22:32:15.246 0                     NaN   NaN
        2014-05-31 12:00:00.000 0                     NaN   NaN

variable                                   circumplex.arousal  \
id      time                    aux_index
AS14.01 2014-02-17 12:04:42.394 0                         NaN
        2014-02-17 18:28:25.520 0                         NaN
        2014-02-18 09:29:51.257 0                         NaN
        2014-02-19 14:43:30.575 0                         NaN
        2014-02-19 17:29:10.378 0                         NaN
...                                                       ...
AS14.33 2014-05-30 22:32:05.016 0                         NaN
        2014-05-30 22:32:11.049 0                         NaN
        2014-05-30 22:32:14.240 0                         NaN
        2014-05-30 22:32:15.246 0                         NaN
        2014-05-31 12:00:00.000 0                        -2.0

variable                                   circumplex.valence  mood  screen  \
id      time                    aux_index
AS14.01 2014-02-17 12:04:42.394 0                         NaN   NaN     NaN
        2014-02-17 18:28:25.520 0                         NaN   NaN     NaN
        2014-02-18 09:29:51.257 0                         NaN   NaN     NaN
        2014-02-19 14:43:30.575 0                         NaN   NaN     NaN
        2014-02-19 17:29:10.378 0                         NaN   NaN     NaN
...                                                       ...   ...     ...
AS14.33 2014-05-30 22:32:05.016 0                         NaN   NaN     NaN
        2014-05-30 22:32:11.049 0                         NaN   NaN     NaN
        2014-05-30 22:32:14.240 0                         NaN   NaN     NaN
        2014-05-30 22:32:15.246 0                         NaN   NaN     NaN
        2014-05-31 12:00:00.000 0                         1.0   7.0     NaN

variable                                   sms
id      time                    aux_index
AS14.01 2014-02-17 12:04:42.394 0          NaN
        2014-02-17 18:28:25.520 0          NaN
        2014-02-18 09:29:51.257 0          NaN
        2014-02-19 14:43:30.575 0          NaN
        2014-02-19 17:29:10.378 0          NaN
...                                        ...
AS14.33 2014-05-30 22:32:05.016 0          NaN
        2014-05-30 22:32:11.049 0          NaN
        2014-05-30 22:32:14.240 0          NaN
        2014-05-30 22:32:15.246 0          NaN
        2014-05-31 12:00:00.000 0          NaN

[358944 rows x 19 columns]

In [59]:
pivot_df = pivot_df.reset_index(level=['id', 'time'])
pivot_df

variable,id,time,activity,appCat.builtin,appCat.communication,appCat.entertainment,appCat.finance,appCat.game,appCat.office,appCat.other,...,appCat.travel,appCat.unknown,appCat.utilities,appCat.weather,call,circumplex.arousal,circumplex.valence,mood,screen,sms
aux_index,,,,,,,,,,,,,,,,,,,,,
0,AS14.01,2014-02-17 12:04:42.394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
0,AS14.01,2014-02-17 18:28:25.520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
0,AS14.01,2014-02-18 09:29:51.257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
0,AS14.01,2014-02-19 14:43:30.575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
0,AS14.01,2014-02-19 17:29:10.378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,AS14.33,2014-05-30 22:32:05.016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6.019,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,AS14.33,2014-05-30 22:32:11.049,NaN,3.122,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,AS14.33,2014-05-30 22:32:14.240,NaN,1.003,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,AS14.33,2014-05-30 22:32:15.246,NaN,4.134,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,AS14.33,2014-05-31 12:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-2.0,1.0,7.0,NaN,NaN

In [60]:
pivot_df[(pivot_df['id'] == 'AS14.01') & (pivot_df['time'] == '2014-04-17 11:00:00.000')]

variable,id,time,activity,appCat.builtin,appCat.communication,appCat.entertainment,appCat.finance,appCat.game,appCat.office,appCat.other,...,appCat.travel,appCat.unknown,appCat.utilities,appCat.weather,call,circumplex.arousal,circumplex.valence,mood,screen,sms
aux_index,,,,,,,,,,,,,,,,,,,,,
0,AS14.01,2014-04-17 11:00:00.000,0.05042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-1.0,1.0,7.0,NaN,NaN
1,AS14.01,2014-04-17 11:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-2.0,0.0,6.0,NaN,NaN